In [2]:
# pandas.dataframe을 사용해 dataframe객체를 만든다. 
# 주로 리스트 딕셔너리 numpy배열 등을 입력으로 받을 수 있다

# 리스트로 dataframe만들기
import pandas as pd

data=[
    [1,'Alice',23],
    [2,'bob',25],
    [3,'kim',27]
]
df = pd.DataFrame(data,columns=['ID','Name','Age'])
df

   ID   Name  Age
0   1  Alice   23
1   2    bob   25
2   3    kim   27

In [3]:
# 딕셔너리로 dataFrame만들기
data = {
    'ID':[1,2,3],
    'Name':['alice','bob','kim'],
    'Age':[23,25,27]
}
df = pd.DataFrame(data)
df

   ID   Name  Age
0   1  alice   23
1   2    bob   25
2   3    kim   27

In [6]:
# 데이터 조회 및 수정 - 특정 열이나 행을 선택해 조회할 수있다

# name 열 선택
print(df['Name'])
# 첫 번째 행 선택
print(df.iloc[0])
# 첫 번째 행의 name의 열 값
print(df.loc[0,'Name'])

0    alice
1      bob
2      kim
Name: Name, dtype: object
ID          1
Name    alice
Age        23
Name: 0, dtype: object
alice

In [11]:
# 행을 추가하거나 삭제할 수 있다

new_row = pd.DataFrame({'ID':[4],'Name':['jj'],'Age':40})
# concat으로 행 추가
df = pd.concat([df,new_row],ignore_index=True)
df

   ID   Name  Age
0   1  alice   23
1   2    bob   25
2   3    kim   27
3   4     jj   40
4   4     jj   40

In [13]:
# 통계적 요약 

# 수치형 데이터의 통계 요약
print(df.describe())
# AGE열의 평균 값
print(df['Age'].mean())

            ID        Age
count  5.00000   5.000000
mean   2.80000  31.000000
std    1.30384   8.336666
min    1.00000  23.000000
25%    2.00000  25.000000
50%    3.00000  27.000000
75%    4.00000  40.000000
max    4.00000  40.000000
31.0

In [14]:
# 데이터 필터링- 조건에 맞는 데이터를 필터링해 주출할 수 있다.
filtered_df = df[df['Age']>24]
filtered_df

   ID Name  Age
1   2  bob   25
2   3  kim   27
3   4   jj   40
4   4   jj   40

In [15]:
# 데이터 정렬
sorted_df = df.sort_values(by='Age', ascending=False)
sorted_df

   ID   Name  Age
4   4     jj   40
3   4     jj   40
2   3    kim   27
1   2    bob   25
0   1  alice   23